#!/bin/bash
set -eu -o pipefail

case $# in
  0) f="" ;;
  1) f=$1 ; shift 1 ;;
  *)
    echo "$0 # compile only" >&2
    echo "$0 <file.elf> # compile and flash" >&2
    exit 2
esac

[ -n "${SERVO_CTRL_NO_CLEAR:-}" ] || clear

(
  set -x
  build="build/simulate"
  if ! [ -d "$build" ]
  then
    mkdir -p "$build"
    cmake -DYALS_HAL="simulate" -DCMAKE_BUILD_TYPE=Debug -G Ninja -S . -B "$build"
  fi
  time ninja -C "$build"
  time ctest --test-dir "$build" --output-on-failure
)

(
  set -x
  build="build/rp2040"
  if ! [ -d "$build" ]
  then
    mkdir -p "$build"
    time ./rp2040_sdk cmake -DYALS_HAL="rp2040" -DCMAKE_BUILD_TYPE=Release -G Ninja -S . -B "$build"
  fi
  time ./rp2040_sdk ninja -C "$build"
  find "$build" -name '*.elf'
)
[ -n "$f" ] || exit 0

(
  set -x
  ls -alh "${f%%.elf}.bin"
  time scp "$f" rp-prog:/tmp/
  time ssh rp-prog rp2040_flash "/tmp/$(basename "$f")"
)
echo OK
