#!/bin/bash
set -eu -o pipefail

case $# in
  0) f="" ;;
  1) f=$1 ; shift 1 ;;
  *)
    echo "$0 # compile only" >&2
    echo "$0 <file.elf> # compile and flash" >&2
    exit 2
esac

clear

(
  set -x
  time ./rp2040_sdk ninja -C build
)
[ -n "$f" ] || exit 0

(
  set -x
  ls -alh "$f"
  time scp "$f" rp-prog:/tmp/
  time ssh rp-prog rp2040_flash "/tmp/$(basename "$f")"
)
echo OK
